### ISSUE TITLE
"bearer" missing?

### ISSUE THREAD

**Issue by goern** [TomasTomecek/show-me#1]
Isnt the word "bearer" missing with your Authorization header?

https://github.com/TomasTomecek/show-me/blob/9ad1c86bc3a22179a2ebb5afb1a1a7f8dcc6afca/show_me/backend.py#L147

**Comment by TomasTomecek** [comment]
Hm, you're right, while looking at Github's docs:

https://developer.github.com/v4/guides/forming-calls/#communicating-with-graphql

It's interesting that it works in the current form, maybe they support both?

Good catch, I'll change it.

**Comment by goern** [comment]
It doesnt matter for querying I guess, the v4 api seems to be very open... did you try it on private repos? or do a mutation?

**Comment by TomasTomecek** [comment]
We are using the v4 API in release-bot: https://github.com/user-cont/release-bot/blob/master/release_bot/github.py

There is a bunch of mutations and it works great. Probably the worst thing is to construct those queries. I recall that someone tried the bot on their private repo and it worked: we only had to change the way the repo is cloned since you can't clone a private repo anonymously over https.
